---
title: "clustering"
author: "Connor Flynn"
date: "6/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stats)
library(here)
library(ClustImpute)
library(factoextra)
library(cluster)
library(gridExtra)
options(scipen = 99)
```

```{r}
sids_data <- read_csv(here("data/sids_data.csv"))
```

```{r}
data <- USArrests
```

```{r}
sids_data <- sids_data %>% 
  remove_rownames %>% 
  column_to_rownames(var="country")

sids_data <- sids_data %>% 
  select(-"region", -"electricity_from_nuclear_fuels") 



for(i in 1:ncol(sids_data)){
  sids_data[is.na(sids_data[,i]), i] <- mean(sids_data[,i], na.rm = TRUE)
}
```

```{r}
sids_data_scaled <- scale(sids_data)
```

```{r}
fviz_nbclust(sids_data_scaled, kmeans, method = "wss")
```




```{r}
km.out <- kmeans(sids_data_scaled, centers = 3, nstart = 100)
```



```{r}
km.cluster <- km.out$cluster

fviz_cluster(list(data = sids_data_scaled, cluster = km.cluster))
```




```{r}
sids_data_scaled_no_singapore <- sids_data_scaled[-44,]
```



```{r}
fviz_nbclust(sids_data_scaled_no_singapore, kmeans, method = "wss")
```




```{r}
km.out.no.singapore <- kmeans(sids_data_scaled_no_singapore, centers = 3, nstart = 100)
```


```{r}
km.cluster.no.singapore <- km.out.no.singapore$cluster

fviz_cluster(list(data = sids_data_scaled_no_singapore, cluster = km.cluster.no.singapore))
```













```{r}
kmeans <- kmeans(sids_data, centers = 10, nstart = 25)
```

```{r}
fviz_cluster(kmeans, data = sids_data)
```



```{r}
set.seed(123)

kmeans(sids_data_no_na, centers = 2, nstart = 25)

kmeans <- ClustImpute(sids_data, 2, nr_iter = 10)

```




