---
title: "Import Data"
author: "Connor Flynn"
date: "5/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
options(scipen = 99)
```

```{r}
factbook_data <- read_csv(here("data/cia-factbook.csv"))
```

```{r}
sids_data <- factbook_data %>% 
  filter(country == "Bahrain" |
         country == "Comoros" |
           country == "Guinea-Bissau" |
           country == "Maldives" |
           country == "Mauritius" |
           country == "Sao-Tome-and-Principe" |
           country == "Seychelles" |
           country == "Singapore" |
           country == "Antigua-and-Barbuda" |
           country == "Bahamas-The" |
           country == "Barbados" |
           country == "Belize" | 
           country == "Cuba" |
           country == "Dominica" |
           country == "Dominican-Republic" |
           country == "Grenada" |
           country == "Guyana" |
           country == "Haiti" | 
           country == "Jamaica" |
           country == "Saint-Kitts-and-Nevis" |
           country == "Saint-Lucia" |
           country == "Saint-Vincent-and-the-Grenadines" |
           country == "Suriname" |
           country == "Trinidad-and-Tobago" |
           country == "Fiji" |
           country == "Kiribati" |
           country == "Marshall-Islands" |
           country == "Micronesia-Federated-States-of" |
           country == "Nauru" |
           country == "Palau" | 
           country == "Papa-New-Guinea" |
           country == "Samoa" |
           country == "Solomon-Islands" |
           country == "Timor-Leste" |
           country == "Tonga" |
           country == "Tuvalu" |
           country == "Vanuatu" |
           country == "American-Samoa" |
           country == "Anguilla" |
           country == "Aruba" |
           country == "Bermuda" |
           country == "British-Virgin-Islands" |
           country == "Cayman-Islands" |
           country == "Cook-Islands" |
           country == "Curacao" |
           country == "French-Polynesia" |
           country == "Guam" |
           country == "Montserrat" |
           country == "New-Caledonia" |
           country == "Niue" |
           country == "Puerto-Rico" |
           country == "Sint-Marteen" |
           country == "Turks-and-Caicos-Islands" |
           country == "Virgin-Islands" |
           country == "Northern-Mariana-Islands" 
           
  )
```

```{r}
AIS <- c("Bahrain", "Comoros", "Guinea-Bissau", "Maldives", "Mauritius", 
         "Sao-Tome-and-Principe", "Seychelles", "Singapore", "Turks-and-Caicos-Islands" )
```


```{r}
Carribean <- c("Antigua-and-Barbuda", "Bahamas-The", "Barbados", "Belize", 
               "Cuba", "Dominica", "Dominican-Republic", "Grenada", "Guyana", "Haiti", "Jamaica", "Saint-Kitts-and-Nevis", "Saint-Lucia", 
           "Saint-Vincent-and-the-Grenadines", "Suriname", "Trinidad-and-Tobago", "Anguilla", "Aruba", "Bermuda", "British-Virgin-Islands", "Cayman-Islands", "Curacao", "Montserrat", "Puerto-Rico", "Sint-Maarteen", "Virgin-Islands")
```


```{r}
Pacific <- c("Fiji", "Kiribati", "Marshall-Islands", "Micronesia-Federated-States-of", "Nauru", "Palau", "Papa-New-Guinea", 
 "Samoa", "Solomon-Islands", "Timor-Leste", "Tonga", "Tuvalu", "Vanuatu",    "American-Samoa", "Northern-Mariana-Islands", "Cook-Islands", "French-Polynesia", "Guam", "New-Caledonia", "Niue")
```


```{r}
sids_data <- sids_data %>% 
  mutate(region = case_when(
    country %in% AIS ~ "AIS",
    country %in% Carribean ~ "Carribean", 
    country %in% Pacific ~ "Pacific"))
```


```{r}
sids_data_col_names <- names(sids_data)
sids_data_col_names

sids_data <- sids_data[, c("gdp_per_capita"                                                              ,
 "labor_force"                         ,
 "crude_oil_production"                                          ,
 "exports"                                                       ,
 "broadband_fixed_subscriptions"                                 ,
 "budget_surplus_deficit"                                        ,
 "carbon_dioxide_emissions_from_consumption_of_energy"           ,
 "country_comparison_airports"                                   ,
 "country_comparison_area"                                         ,
 "country_comparison_birth_rate"                                   ,
 "country_comparison_children_under_the_age_of_5_years_underweight",
 "country_comparison_death_rate"                                   ,
 "country_comparison_education_expenditures"                       ,
 "country_comparison_hiv_aids_adult_prevalence_rate"               ,
 "country_comparison_hiv_aids_deaths"                              ,
 "country_comparison_hiv_aids_people_living_with_hiv_aids"         ,
 "country"                                                  ,
 "gdp_real_growth_rate"                                            ,
 "gross_national_saving"                                           ,
 "imports"                                                         ,
 "industrial_production_growth_rate"                               ,
 "inflation_rate"                                                  ,
 "internet_users"                                                  ,
 "country_comparison_infant_mortality_rate"                                                     ,
 "natural_gas_consumption"                                         ,
 "natural_gas_exports"                                             ,
 "natural_gas_imports"                                             ,
 "natural_gas_production"                                          ,
 "natural_gas_proved_reserves"                                     ,
 "public_debt"                                                     ,
 "refined_petroleum_products_consumption"                          ,
 "refined_petroleum_products_exports"                              ,
 "refined_petroleum_products_imports"                              ,
 "refined_petroleum_products_production"                           ,
 "reserves_of_foreign_exchange_and_gold"                           ,
 "taxes_and_other_revenues"                                        ,
 "telephones_fixed_lines"                                          ,
 "telephones_mobile_cellular"                                      ,
 "unemployment_rate"                                               ,
 "crude_oil_proved_reserves"                                       ,
 "current_account_balance"                                         ,
 "debt_external"                                                   ,
 "electricity_consumption"                                         ,
 "electricity_exports"                                             ,
 "electricity_from_fossil_fuels"                                   ,
 "electricity_from_hydroelectric_plants"                           ,
 "electricity_from_nuclear_fuels"                                  ,
 "electricity_from_other_renewable_sources"                        ,
 "electricity_imports"                                             ,
 "electricity_installed_generating_capacity"                       ,
 "electricity_production"                                          ,
 "country_comparison_life_expectancy_at_birth"                     ,
 "country_comparison_maternal_mortality_rate"                      ,
 "country_comparison_median_age"                                   ,
 "country_comparison_merchant_marine"                              ,
 "country_comparison_military_expenditures"                        ,
 "country_comparison_net_migration_rate"                           ,
 "country_comparison_obesity_adult_prevalence_rate"                ,
 "country_comparison_population"                                   ,
 "country_comparison_population_growth_rate"                       ,
 "country_comparison_railways"                                     ,
 "country_comparison_roadways"                                     ,
 "country_comparison_total_fertility_rate"                         ,
 "country_comparison_unemployment_youth_ages_15_24"                ,
 "country_comparison_waterways"                                    ,
 "crude_oil_exports"                                               ,
 "crude_oil_imports"                                               ,
 "region")  ]
```

```{r}
write_csv(sids_data, here("data/sids_data.csv"))
```

