---
title: "SIDS CIA World Factbook Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
    theme: paper
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(ggplot2)
# library(mgcv)
library(shiny)
library(flexdashboard)
library(tidyverse)
library(here)
library(plotly)
library(ggiraph)
options(scipen = 99)


```



```{r}
factbook_data <- read_csv(here("data/cia-factbook.csv"))
```

```{r}
sids_data <- factbook_data %>% 
  filter(country == "Bahrain" |
         country == "Comoros" |
           country == "Guinea-Bissau" |
           country == "Maldives" |
           country == "Mauritius" |
           country == "Sao-Tome-and-Principe" |
           country == "Seychelles" |
           country == "Singapore" |
           country == "Antigua-and-Barbuda" |
           country == "Bahamas-The" |
           country == "Barbados" |
           country == "Belize" | 
           country == "Cuba" |
           country == "Dominica" |
           country == "Dominican-Republic" |
           country == "Grenada" |
           country == "Guyana" |
           country == "Haiti" | 
           country == "Jamaica" |
           country == "Saint-Kitts-and-Nevis" |
           country == "Saint-Lucia" |
           country == "Saint-Vincent-and-the-Grenadines" |
           country == "Suriname" |
           country == "Trinidad-and-Tobago" |
           country == "Fiji" |
           country == "Kiribati" |
           country == "Marshall-Islands" |
           country == "Micronesia-Federated-States-of" |
           country == "Nauru" |
           country == "Palau" | 
           country == "Papa-New-Guinea" |
           country == "Samoa" |
           country == "Solomon-Islands" |
           country == "Timor-Leste" |
           country == "Tonga" |
           country == "Tuvalu" |
           country == "Vanuatu" |
           country == "American-Samoa" |
           country == "Anguilla" |
           country == "Aruba" |
           country == "Bermuda" |
           country == "British-Virgin-Islands" |
           country == "Cayman-Islands" |
           country == "Cook-Islands" |
           country == "Curacao" |
           country == "French-Polynesia" |
           country == "Guam" |
           country == "Montserrat" |
           country == "New-Caledonia" |
           country == "Niue" |
           country == "Puerto-Rico" |
           country == "Sint-Marteen" |
           country == "Turks-and-Caicos-Islands" |
           country == "Virgin-Islands" |
           country == "Northern-Mariana-Islands" 
           
  )
```

```{r}
AIS <- c("Bahrain", "Comoros", "Guinea-Bissau", "Maldives", "Mauritius", 
         "Sao-Tome-and-Principe", "Seychelles", "Singapore", "Turks-and-Caicos-Islands" )
```


```{r}
Carribean <- c("Antigua-and-Barbuda", "Bahamas-The", "Barbados", "Belize", 
               "Cuba", "Dominica", "Dominican-Republic", "Grenada", "Guyana", "Haiti", "Jamaica", "Saint-Kitts-and-Nevis", "Saint-Lucia", 
           "Saint-Vincent-and-the-Grenadines", "Suriname", "Trinidad-and-Tobago", "Anguilla", "Aruba", "Bermuda", "British-Virgin-Islands", "Cayman-Islands", "Curacao", "Montserrat", "Puerto-Rico", "Sint-Maarteen", "Virgin-Islands")
```


```{r}
Pacific <- c("Fiji", "Kiribati", "Marshall-Islands", "Micronesia-Federated-States-of", "Nauru", "Palau", "Papa-New-Guinea", 
 "Samoa", "Solomon-Islands", "Timor-Leste", "Tonga", "Tuvalu", "Vanuatu",    "American-Samoa", "Northern-Mariana-Islands", "Cook-Islands", "French-Polynesia", "Guam", "New-Caledonia", "Niue")
```


```{r}
sids_data <- sids_data %>% 
  mutate(region = case_when(
    country %in% AIS ~ "AIS",
    country %in% Carribean ~ "Carribean", 
    country %in% Pacific ~ "Pacific"))
```





```{r}
dataset <- sids_data
```



Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
checkboxInput('jitter', 'Jitter', value = TRUE)
checkboxInput('smooth', 'Smooth', value = FALSE)

selectInput('x', 'X', names(dataset))
selectInput('y', 'Y', names(dataset), names(dataset)[[2]])
selectInput('color', 'Color', c('None', names(dataset)))

selectInput('facet_row', 'Facet Row',
c(None='.', names(dataset)))
selectInput('facet_col', 'Facet Column',
c(None='.', names(dataset)))
```

Outputs
-----------------------------------------------------------------------

### Data

```{r}


renderggiraph({
  p <- ggplot(data = dataset, aes_string(x=input$x, y=input$y)) + geom_point()

  my_gg <- p + geom_point_interactive(aes(tooltip = country), size = 2)
  if (input$color != 'None')
    my_gg <- my_gg + aes_string(color=input$color)

  facets <- paste(input$facet_row, '~', input$facet_col)
  if (facets != '. ~ .')
    my_gg <- my_gg + facet_grid(facets)

  if (input$jitter)
    my_gg <- my_gg + geom_jitter()
  if (input$smooth)
    my_gg <- my_gg + geom_smooth()

    print(girafe(code=print(my_gg)))
})


```

